# Configuration on how the Github release behave.

# How the change log is collected
changelog:
  #exclude:
  #  labels:
  #    - ignore-for-release
  #  authors:
  #    - github-bots
  categories:
    - title: Features
      labels:
        - enhancement
        - feature request
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
